### ISSUE TITLE
(1.18.2 | Nature's Compass 1.9.7) Crash upon trying to locate a biome.

### ISSUE THREAD

**Issue by Lesley-Black-Velvet** [MattCzyr/NaturesCompass#146]
Good evening!

I tried to find a savanna biome in my world, unfortunately, the game suddenly crashed upon commencing the search. 

`
Time: 9/21/22, 8:02 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?] {re:mixin}
	at java.util.Optional.of(Optional.java:113) ~[?:?] {re:mixin}
	at com.chaosthedude.naturescompass.util.BiomeUtils.getKeyForBiome(BiomeUtils.java:37) ~[NaturesCompass-1.18.2-1.9.7-forge.jar%23164!/:1.18.2-1.9.7-forge] {re:classloading}
	at com.chaosthedude.naturescompass.util.BiomeSearchWorker.doWork(BiomeSearchWorker.java:90) ~[NaturesCompass-1.18.2-1.9.7-forge.jar%23164!/:1.18.2-1.9.7-forge] {re:classloading}
	at net.minecraftforge.common.WorldWorkerManager.tick(WorldWorkerManager.java:37) ~[forge-1.18.2-40.1.80-universal.jar%23236!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeInternalHandler.onServerTick(ForgeInternalHandler.java:69) ~[forge-1.18.2-40.1.80-universal.jar%23236!/:?] {re:mixin,re:classloading,pl:mixin:APP:pollen.mixins.json:ForgeInternalHandlerMixin,pl:mixin:A}
	at net.minecraftforge.eventbus.ASMEventHandler_915_ForgeInternalHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactory.java:953) ~[forge-1.18.2-40.1.80-universal.jar%23236!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:879) ~[client-1.18.2-20220404.173914-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23231!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:blueprint.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

`

**Comment by Gunner76th** [comment]
It generally helps to have the FULL crash report file and more details about the other mods being used. Snippets like this usually dont help much.
