### ISSUE TITLE
Crashing on Search

### ISSUE THREAD

**Issue by CyberPunk2064** [MattCzyr/NaturesCompass#68]
Running Forge 34.1.0 and 1.8.5 of this mod, completely crashes the game every time I choose a biome and click search. Running the latest Biomes O'Plenty with it on a brand new 1.16.3 server. What am I doing wrong?

**Comment by MattCzyr** [comment]
Please post the crash report associated with this issue.

**Comment by CyberPunk2064** [comment]
[28-Sep-2020 11:14:40] [INFO] Starting search: 64 sample space, 10000 max radius

[28-Sep-2020 11:14:40] [ERROR] Exception caught during firing event: null

[28-Sep-2020 11:14:40] Index: 1

[28-Sep-2020 11:14:40] Listeners:

[28-Sep-2020 11:14:40] 0: NORMAL

[28-Sep-2020 11:14:40] 1: ASM: net.minecraftforge.common.ForgeInternalHandler@213fff15 onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V

[28-Sep-2020 11:14:40] java.lang.NullPointerException

[28-Sep-2020 11:14:40] at com.chaosthedude.naturescompass.util.BiomeSearchWorker.doWork(BiomeSearchWorker.java:86)

[28-Sep-2020 11:14:40] at net.minecraftforge.common.WorldWorkerManager.tick(WorldWorkerManager.java:51)

[28-Sep-2020 11:14:40] at net.minecraftforge.common.ForgeInternalHandler.onServerTick(ForgeInternalHandler.java:80)

[28-Sep-2020 11:14:40] at net.minecraftforge.eventbus.ASMEventHandler_31_ForgeInternalHandler_onServerTick_ServerTickEvent.invoke(.dynamic)

[28-Sep-2020 11:14:40] at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)

[28-Sep-2020 11:14:40] at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)

[28-Sep-2020 11:14:40] at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:120)

[28-Sep-2020 11:14:40] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:823)

[28-Sep-2020 11:14:40] at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:637)

[28-Sep-2020 11:14:40] at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229)

[28-Sep-2020 11:14:40] at java.lang.Thread.run(Thread.java:748)

[28-Sep-2020 11:14:40] [ERROR] Encountered an unexpected exception

[28-Sep-2020 11:14:40] java.lang.NullPointerException: null

[28-Sep-2020 11:14:40] at com.chaosthedude.naturescompass.util.BiomeSearchWorker.doWork(BiomeSearchWorker.java:86) ~[?:1.16.3-1.8.5] {re:classloading}

[28-Sep-2020 11:14:40] at net.minecraftforge.common.WorldWorkerManager.tick(WorldWorkerManager.java:51) ~[?:?] {re:classloading}

[28-Sep-2020 11:14:40] at net.minecraftforge.common.ForgeInternalHandler.onServerTick(ForgeInternalHandler.java:80) ~[?:?] {re:classloading}

[28-Sep-2020 11:14:40] at net.minecraftforge.eventbus.ASMEventHandler_31_ForgeInternalHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?] {}

[28-Sep-2020 11:14:40] at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}

[28-Sep-2020 11:14:40] at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}

[28-Sep-2020 11:14:40] at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:120) ~[?:?] {re:classloading}

[28-Sep-2020 11:14:40] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:823) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}

[28-Sep-2020 11:14:40] at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:637) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}

[28-Sep-2020 11:14:40] at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}

[28-Sep-2020 11:14:40] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}

[28-Sep-2020 11:14:43] [Prisma] Server shut down. Cleaning up...

[28-Sep-2020 11:14:43] [Prisma] Server stopped.
